name: Run Performance Comparison

on:
  pull_request:
    types: [ labeled, issue_comment ]

jobs:
  build:
    if: ${{ github.event.label.name == 'run-performance-comparison' }}
    runs-on: ubuntu-latest

    steps:
    - name: Remove run-performance-comparison label
      uses: actions-ecosystem/action-remove-labels@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: run-performance-comparison

    - name: Parse Comment For performance-comparison Args
      if: ${{ startsWith(github.event.comment.body, '/run-performance-comparison') }}
      run: |
        echo "hello world"

    - name: Comment on PR
      uses: actions/github-script@v4
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'test comment!'
          })