name: Run Performance Comparison Parse Comment

on:
  issue_comment:
    types: [created]

jobs:
  remove_label:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Parse Comment For performance-comparison Args
      if: ${{ startsWith(github.event.comment.body, '/run-performance-comparison') }}
      run: |
        echo $( tail -n +2 <<< "${{ github.event.comment.body }}") > out.yaml

    - name: yaml-lint
      uses: ibiqlik/action-yamllint@v3
      with:
        file_or_dir: out.yaml